#version: "3.8"
#services:
#  hugo:
#    container_name: hugo
#    image: debian:12.4-slim
#    build: .
#    working_dir: /usr/src
#    command: hugo server -p 8080 --bind 0.0.0.0 --theme hugo-coder --disableFastRender
#    ports:
#     - 8080:8080
#    tty: true
#
version: "3.8"
services:
  hugo:
    container_name: hugo
    build: .
    command: server -p 8080 --bind 0.0.0.0 --theme hugo-coder --disableFastRender
    #volumes:
    #- ".:/src"
    ports:
      - "8080:8080"
      - "1313:1313"
      #
    #tty: true
