# use: https://github.com/jpanther/lynx
# CSS は assets/css/custom.css

baseURL = "https://rayfiyo.github.io"
copyright = "Copy, _right?_ :thinking_face:"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "term", "RSS", "sitemap"]
enableEmoji = true
hasCJKLanguage = true
languageCode = "ja"
title = "rayfiyo"


[params.author]
  name = "rayfiyo<br>　"
  headline = "Gopherくん が好きです！！！ʕ ◔ ϖ ◔ʔ"
  image = "img/icon.jpeg"

  # icon = "" を使うことで assets/icons のアイコンを明示的に指定可能
  # https://github.com/jpanther/lynx/blob/dev/config.toml
  links = [
    { github = "https://github.com/rayfiyo" },
    { zenn = { href = "https://zenn.dev/rayfiyo", text = "Zenn" } },
    { twitter = "https://twitter.com/rayfiyo" },
    { x = "https://x.com/rayfiyo" },
    { discord = "https://discord.com/invite/6BvQyYms" },
    { bluesky = "https://bsky.app/profile/did:plc:ronxumipfy4ct5y22tmqtkh7" },
    { mixi2 = { href = "https://mixi.social/@rayfiyo", text = "mixi2" } },
    { qiita = { href = "https://qiita.com/rayfiyo", text = "Qiita" } },
    { hackermeshi = { href = "https://hackermeshi.com/profiles/1650", text = "ハッカー飯" } },
    { note = { href = "https://note.com/rayfiyo", text = "note" } },
  ]

[params.author.en]
  headline = "I like The Go gopher ʕ ◔ ϖ ◔ʔ"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
